---
controller_user_accounts:
- username: "admin"
  password: "redhat00"
  email: "admin@example.com"
  first_name: ""
  last_name: ""
  auditor: "False"
  superuser: "True"
  update_secrets: False
...
