---
controller_projects:
  - name: "Controller CasC Examples Project"
    description: ""
    organization: "Recursive Workflows"
    scm_type: "git"
    scm_url: "https://github.com/automationiberia/controller-casc-examples.git"
    scm_branch: ""
    scm_clean: "False"
    scm_delete_on_update: "False"
    scm_update_on_launch: "False"
    scm_update_cache_timeout: "0"
    allow_override: "False"
    timeout: 0
...
