---
controller_workflows:
  - name: "RecursiveWorkflowsMainWorkflow"
    description: ""
    organization: "Recursive Workflows"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "b0f1be76-649a-4a21-9e4b-c5ca652bda95"
        workflow_job_template: "MainWorkflow"
        unified_job_template: "RecursiveWorkflowsWorkflow2"
        organization: "Recursive Workflows"
        all_parents_must_converge: "False"
      - identifier: "31df88f5-d6e4-45ec-b4fa-60bbe91b6600"
        workflow_job_template: "MainWorkflow"
        unified_job_template: "RecursiveWorkflowsWorkflow1"
        organization: "Recursive Workflows"
        all_parents_must_converge: "False"
        success_nodes:
          - b0f1be76-649a-4a21-9e4b-c5ca652bda95
    survey_enabled: "False"
    ask_variables_on_launch: "False"
    allow_simultaneous: "False"
    scm_branch: ""
    webhook_service: ""
    survey_enabled: False
    survey_spec: {}
...
