---
controller_workflows:
  - name: "ParameterizedWorkflow1"
    description: ""
    organization: "Recursive Workflows"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "ParameterizedWorflow1Node1"
        workflow_job_template: "ParameterizedWorkflow1"
        unified_job_template: "Parameterized Job Template"
        organization: "Recursive Workflows"
        all_parents_must_converge: "False"
        extra_data:
          param2: World
    survey_enabled: "False"
    ask_variables_on_launch: "False"
    allow_simultaneous: "False"
    scm_branch: ""
    webhook_service: ""
    survey_enabled: False
    survey_spec: {}
...
