---
controller_credentials:
  - name: "Recursive Workflows Credential"
    description: ""
    credential_type: "Machine"
    organization: "Recursive Workflows"
    inputs:
      username: admin

...
