---
controller_groups:
  - name: ad1
    description: Hosts registered to Active Directory 1
    inventory: "Recursive Workflows Inventory"
    variables:
      myvars: example1
    hosts:
      - host1
  - name: ad2
    description: Hosts registered to Active Directory 2
    inventory: "Recursive Workflows Inventory"
    variables:
      myvars: example2
    hosts:
      - host2
...
