---
controller_groups:
  - name: "AD1 Credential"
    description: "Hosts registered to Active Directory 1"
    inventory: "Recursive Workflows Inventory"
    variables:
      myvars: example1
    hosts:
      - host1
  - name: "AD2 Credential"
    description: "Hosts registered to Active Directory 2"
    inventory: "Recursive Workflows Inventory"
    variables:
      myvars: example2
    hosts:
      - host2
...
