---
controller_credentials:
  - name: "CONTROLLER-Git-Credential"
    description: ""
    credential_type: "Source Control"
    organization: "CONTROLLER-ORG"
    inputs:
      ssh_key_data: "{{ vault_git_ssh_key_data }}"
      username: awx-git-cred-temp

...
