---
controller_credentials:
  - name: "CONTROLLER-HUB-Cluster-Kubeconfig"
    description: ""
    credential_type: "Kubeconfig"
    organization: "CONTROLLER-ORG"
    inputs:
      kube_config: "{{ vault_hub_kubeconfig_file_content }}"

...
