---
controller_credentials:
  - name: "CONTROLLER-Machine Credential"
    description: ""
    credential_type: "Machine"
    organization: "CONTROLLER-ORG"
    inputs:
      password: "{{ vault_user_aap_pwd }}"
      username: admin

...
