---
controller_schedules:
  - name: "Cleanup Expired Sessions"
    description: "Cleans out expired browser sessions"
    enabled: True
    unified_job_template: "Cleanup Expired Sessions"
    dtstart: "2023-12-13T08:17:50Z"
    dtend: ""
    timezone: "UTC"
    rrule: "DTSTART:20231213T081750Z RRULE:FREQ=WEEKLY;INTERVAL=1"
    extra_data:
      {}
    scm_branch: ""
    forks: 0
    job_slice_count: 0
    timeout: 0
    job_type: ""
    job_tags: ""
    skip_tags: ""
    limit: ""
    verbosity: 0
...
