---
controller_instance_groups:
  - name: "controlplane"
    policy_instance_minimum: "0"
    policy_instance_percentage: "100"
    instances:
      - "aap-all-in-one.iam.lab"
  - name: "default"
    policy_instance_minimum: "0"
    policy_instance_percentage: "100"
    instances:
      - "aap-all-in-one.iam.lab"
...
