---
controller_credential_types:
  - name: "Kubeconfig"
    description: ""
    kind: "cloud"
    inputs:
      fields:
      - id: kube_config
        label: kubeconfig
        multiline: true
        secret: true
        type: string
      required:
      - kube_config

    injectors:
      env:
        K8S_AUTH_KUBECONFIG: !unsafe '{{ tower.filename.kubeconfig }}'
      file:
        template.kubeconfig: !unsafe '{{ kube_config }}'
  - name: "REST API Credential"
    description: "REST API Credential"
    kind: "cloud"
    inputs:
      fields:
      - id: rest_username
        label: REST Username
        type: string
      - id: rest_password
        label: REST Password
        secret: true
        type: string
      required:
      - rest_username
      - rest_password

    injectors:
      env:
        rest_password_env: !unsafe '{{ rest_password }}'
        rest_username_env: !unsafe '{{ rest_username }}'
      extra_vars:
        rest_password: !unsafe '{{ rest_password }}'
        rest_username: !unsafe '{{ rest_username }}'
...
