---
controller_execution_environments:
  - name: "My EE"
    description: ""
    image: "quay.io/ansible/awx-ee"
    pull: "always"
  - name: "ee-casc"
    description: ""
    image: "quay.io/automationiberia/casc/ee-casc"
    pull: "always"
...
