---
- hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: "Determine if pre-tasks must be executed or not"
      ansible.builtin.set_fact:
        _input_credential: "{{ input_credential is defined }}"

    - name: "Block to be run when no input credential is specified"
      when:
        - _input_credential is defined
        - not _input_credential
        - inventory_hostname in groups.ad1 or inventory_hostname in groups.ad2
      block:
        - name: "Determine the credential to be used"
          ansible.builtin.set_fact:
            input_credential: "{{ 'AD1 Credential' if inventory_hostname in groups.ad1 else 'AD2 Credential' if inventory_hostname in groups.ad2 }}"

        - name: "Show the credential to be used"
          ansible.builtin.debug:
            msg: "The credential to be used is: {{ input_credential }}"

        - name: "Launch the same job with the correct credential"
          awx.awx.job_launch:
            job_template: "Recursive Job Template Multi File"
            credentials:
              - "{{ input_credential }}"
          register: job

        - name: Wait for job max 120s
          awx.awx.job_wait:
            job_id: "{{ job.id }}"
            timeout: 120

        # - name: "Launch the same job with the correct credentials"
        #   awx.awx.job_launch:
        #     controller_username: "{{ vault_controller_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
        #     controller_password: "{{ vault_controller_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
        #     controller_host: "{{ vault_controller_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"
        #     validate_certs: false
        #     credentials:


- ansible.builtin.import_playbook: recursive-playbook-multi-file-target.yaml
  when:
    - _input_credential is defined
    - _input_credential
...
