---
- name: "Playbook to show the input parameters"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    input_vars:
      - param1
      - param2
      - output
  tasks:
    - name: "Show the input variables"
      ansible.builtin.debug:
        var: "{{ current_var }}"
      loop: "{{ input_vars }}"
      loop_control:
        loop_var: current_var
    - name: "Set the output parameters for the next node"
      ansible.builtin.set_stats:
        data:
          output: "{{ param1 | default('no param 1') }} - {{ param2 | default('no param 2') }}"
...
