---
- name: "Playbook for task1"
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - task1
  tasks:
    - name: "Task 1"
      debug:
        var: ansible_facts
    - name: "Task 2"
      debug:
        var: "{{ item }}"
      loop:
        - task1_output
        - task2_output
        - task3_output
    - name: "Set task1 output"
      ansible.builtin.set_stats:
        data:
          task1_output: "Output 1"
...
