---
- name: "Playbook for task3"
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - task3
  tasks:
    - name: "Task 3"
      debug:
        var: ansible_facts
    - name: "Task 2"
      debug:
        var: "{{ item }}"
      loop:
        - task1_output
        - task2_output
        - task3_output
    - name: "Set task3 output"
      ansible.builtin.set_stats:
        data:
          task3_output: "Output 3"
...

