---
- name: "Playbook for task2"
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - task2
  tasks:
    - name: "Task 2"
      debug:
        var: ansible_facts
    - name: "Task 2"
      debug:
        var: "{{ item }}"
      loop:
        - task1_output
        - task2_output
        - task3_output
    - name: "Set task2 output"
      ansible.builtin.set_stats:
        data:
          task2_output: "Output 2"
...

